theme: jekyll-theme-cayman
title: Woo Product Cart Title
twitter_username: jcasabona
github_username:  jcasabona
repo: https://github.com/jcasabona/woocommerce-product-cart-title/
show_downloads: true
zip_url: https://github.com/jcasabona/woocommerce-product-cart-title/archive/master.zip
